---
version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node8:
          filters:
            tags:
              only: /.*/
      - node10:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - node8
            - node10
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - node8
            - node10
          filters:
            tags:
              only: /.*/

jobs:
  node8:
    docker:
      - image: node:8@sha256:b802a02ee6496c34e2dc0eb0379eb1c738331414956d650c0dffdfa0866acb2f
        user: node
    steps: &unit_tests_steps
      - checkout
      - run: &npm_install
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Run unit tests.
          command: npm test
      - run:
          name: Submit coverage data to codecov.
          command: node_modules/.bin/codecov
          when: always
  node10:
    docker:
      - image: node:10@sha256:c9b66b96a3a8f1141fef55874157f28c2825990b557fce798676e2f979b7009a
        user: node
    steps: *unit_tests_steps
  lint:
    docker:
      - image: node:10@sha256:c9b66b96a3a8f1141fef55874157f28c2825990b557fce798676e2f979b7009a
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Run linting.
          command: npm run lint

  docs:
    docker:
      - image: node:10@sha256:c9b66b96a3a8f1141fef55874157f28c2825990b557fce798676e2f979b7009a
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Build documentation.
          command: npm run docs
