---
version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node8:
          filters:
            tags:
              only: /.*/
      - node9:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - node8
            - node9
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - node8
            - node9
          filters:
            tags:
              only: /.*/

jobs:
  node8:
    docker:
      - image: node:8@sha256:26e4c77f9f797c3993780943239fa79419f011dd93ae4e0097089e2145aeaa24
        user: node
    steps: &unit_tests_steps
      - checkout
      - run: &npm_install
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Run unit tests.
          command: npm test
      - run:
          name: Submit coverage data to codecov.
          command: node_modules/.bin/codecov
          when: always
  node9:
    docker:
      - image: node:9@sha256:84defd39d4694815086f11e3f293b7dbc3bae0742ad9691824111420954920b1
        user: node
    steps: *unit_tests_steps
  lint:
    docker:
      - image: node:8@sha256:26e4c77f9f797c3993780943239fa79419f011dd93ae4e0097089e2145aeaa24
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Run linting.
          command: npm run lint

  docs:
    docker:
      - image: node:8@sha256:26e4c77f9f797c3993780943239fa79419f011dd93ae4e0097089e2145aeaa24
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Build documentation.
          command: npm run docs
