---
version: 2.0
workflows:
  version: 2
  tests:
    jobs:
      - node8:
          filters:
            tags:
              only: /.*/
      - node10:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - node8
            - node10
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - node8
            - node10
          filters:
            tags:
              only: /.*/

jobs:
  node8:
    docker:
      - image: node:8@sha256:bba8a9c445fefc3e53fb2dfdfa755b0c119ae9f9999637e3b96ea37fae89d5d0
        user: node
    steps: &unit_tests_steps
      - checkout
      - run: &npm_install
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Run unit tests.
          command: npm test
      - run:
          name: Submit coverage data to codecov.
          command: node_modules/.bin/codecov
          when: always
  node10:
    docker:
      - image: node:10@sha256:2cda73dd26369c2ec69130ddda6f83ff4980fd6fc8e73b5e670a7670d4c86ba0
        user: node
    steps: *unit_tests_steps
  lint:
    docker:
      - image: node:10@sha256:2cda73dd26369c2ec69130ddda6f83ff4980fd6fc8e73b5e670a7670d4c86ba0
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Run linting.
          command: npm run lint

  docs:
    docker:
      - image: node:10@sha256:2cda73dd26369c2ec69130ddda6f83ff4980fd6fc8e73b5e670a7670d4c86ba0
        user: node
    steps:
      - checkout
      - run: *npm_install
      - run:
          name: Build documentation.
          command: npm run docs
